### ISSUE TITLE
Install fails :  Failed to open dir: plugins:// does not exist.

### ISSUE THREAD

**Issue by jerryhopper** [mwalbeck/docker-getgrav#2]
Thanks for the arm64 support!

But when running the container, the command : bin/grav install  fails with: **Failed to open dir: plugins:// does not exist.**
i will try investigate the issue later today when im home.

<pre>
app_1  | 24 packages you are using are looking for funding.
app_1  | Use the `composer fund` command to find out more!
app_1  |
app_1  |
app_1  |
app_1  | In UniformResourceIterator.php line 102:
app_1  |
app_1  |   Failed to open dir: plugins:// does not exist.
app_1  |
app_1  |
app_1  | install [-s|--symlink] [-p|--plugin PLUGIN] [-t|--theme THEME] [--] [<destination>]
</pre>

**Comment by mwalbeck** [comment]
I should probably mention this in the README, and it could be a nice improvement, but currently the image doesn't generate a user folder for you if there isn't one and with GRAV 1.7 the install commands needs it to be present, so that is the reason for the error. If you would like a skeleton base to get started with you can download GRAV from their website and pull out the user folder and use that.

**Comment by jerryhopper** [comment]
oh, dang!   Silly me.  thanks for clearing that up.
